### ISSUE TITLE
SyntaxError: invalid syntax print(*args, file=sys.stderr, **kwargs)      

### ISSUE THREAD

**Issue by omyhub** [sripathikrishnan/redis-rdb-tools#111] opened 2018-01-09 09:01 UTC
[root@azb128 ~]# rdb --command json  dump.rdb 
Traceback (most recent call last):
  File "/usr/bin/rdb", line 9, in <module>
    load_entry_point('rdbtools==0.1.12', 'console_scripts', 'rdb')()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 378, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2566, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2260, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/lib/python2.7/site-packages/rdbtools-0.1.12-py2.7.egg/rdbtools/cli/rdb.py", line 11
    print(*args, file=sys.stderr, **kwargs)
          ^
SyntaxError: invalid syntax
I  don't known why really ... WTF

[root@azb128 ~]# python --version 
Python 2.7.5
[root@azb128 ~]# ls -lh dump.rdb  
-rw-r--r--. 1 root root 32M 1月   9 16:05 dump.rdb

**Comment by omyhub** [comment] 2018-01-09 09:01
someone help me , please !

**Comment by oranagra** [comment] 2018-01-09 09:13
@sripathikrishnan looks like a regression from https://github.com/sripathikrishnan/redis-rdb-tools/commit/391008bdd46d7c9b8968043b4035cfe40e695ce3
@omyhub please use the 'stable' branch instead.

**Comment by sripathikrishnan** [comment] 2018-01-09 12:11
@omyhub this should be fixed in master as well. Sorry for the inconvenience!

**Closed by sripathikrishnan** 2018-01-09 12:11 UTC

**Comment by omyhub** [comment] 2018-01-10 01:52
thanks
